name: 01.02.2022

on:
 push:
  branches: [ main ]
 pull_request:
  branches: [ main ]

 workflow_dispatch:
 
env:
 global_env: global


jobs:
 sys_info:
  runs-on: ubuntu-latest
  env:
   local_env: job

  steps:
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
   - uses: actions/checkout@v2

   - name: Run a one-line script
     run: echo Hello, world!

   - name: user
     run: uname
   - name: sysinfo
     run: |
       pwd
       lshw

   - name: print env
     run: echo ${{ github.job }}

 build:
  runs-on: ubuntu-latest
  env:
   local_env: job_print_env

  steps:
    - name: build
      run: |
          sleep 15
          echo "test build" >> build.txt  

 test:
  runs-on: ubuntu-latest
  needs: [build, sys_info]
  steps:
    - name: run_test
      run: sleep 20
